---
# tasks file for ec2_launch
# tasks file for ec2_launch

- name: adding ssh access to a security group
  amazon.aws.ec2_group:
    name: default
    description: security group for ec2 instances
    region: ap-south-1
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

      - proto: tcp
        from_port: 3001
        to_port: 3001
        cidr_ip: 0.0.0.0/0

    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: security_group


- name: Launch Ec2 instances
  amazon.aws.ec2_instance:
    name: Ansible-created-instance
    key_name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami_id }}"
    count: 11
    security_group: "{{ security_group.group_id }}"
  register: ec2_instances


- name: Wait for instances to be ready
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  loop: "{{ ec2_instances.instances }}"
  when: ec2_instances is defined and ec2_instances.instances | length > 0

- name: Add the EC2 instances to the Ansible inventory
  add_host:
    name: "{{ item.public_dns_name }}"
    group: ec2_instances
    ansible_ssh_private_key_file: "{{ ec2_key_path }}"
    ansible_user: ec2-user
  loop: "{{ ec2_instances.instances }}"


- name: Debug ssh key path
  debug:
    var: ec2_key_path

- name: Debug dynamic inventory
  debug:
    var: groups['ec2_instances']
